### ISSUE TITLE
Name of Project too long?

### ISSUE THREAD

**Issue by jimshelley** [OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations#1]
I was unable to build the project because the name was too long. Renaming the projects and solution file didn't seem to help either.

**Comment by Rick-Kirkham** [comment]
Visual Studio doesn't like long paths. If you extract to the drive root (C:), it will be short enough.

**Comment by jimshelley** [comment]
That worked - Thank you!

**Comment by Rick-Kirkham** [comment]
closing
