### ISSUE TITLE
Communication with the Sharepoint server is canceled

### ISSUE THREAD

**Issue by michaeloxygen** [OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations#2]
Hey Guys,
I'm looking into creating a pretty simple display feature on our .NET intranet that fetches links to Sharepoint files in a specific folder in a list on our Office365 Sharepoint.

I have fetched your Sample packagem followed the steps and changed the Site URL, have the Add-in authenticate myself against my Sharepoint installation, but when I run the Add-in project (Not the web project) I get an error stating "Sideloadning of apps is not enabled on this site". I'm not a Sharepoint expert, but have some Admin experience, when googling the error I get that it's not adviseable to allow on production? (We're just a small company that use Sharepoint Online for document management and we don't have any development environment for Sharepoint related features as this is our first integration).

How do I enable that on Sharepoint (if at all) in order to do this or what could I be missing/doing wrong?

**Comment by Rick-Kirkham** [comment]
The error "Sideloading of apps is not enabled on this site" means that the feature that is needed to enable a SharePoint site collection to be a test site for add-in development is not enabled on the site collection. The easiest way to deal with this is to create a site collection using the **Developer Site** type. (The feature is automatically enabled on that type of site.) Use the root of that site collection, or a subsite you create within it, as your test SharePoint site. For a test site on O365, the instructions are here: https://msdn.microsoft.com/en-us/library/office/jj692554.aspx. For an on premises test site, the instructions are here: https://msdn.microsoft.com/en-us/library/office/fp179923.aspx
