### ISSUE TITLE
Markdown error in ReadMe.md

### ISSUE THREAD

**Issue by RicardoSilveira23** [OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations#4]
Page Link:
https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations/blob/master/ReadMe.md

Additional resources title is wrongly formatted, from the raw markdown seems like a misplaced <a> tag?

![capture](https://user-images.githubusercontent.com/24255374/39753816-00ced39a-52b8-11e8-974f-f9184174cd59.PNG)

**Comment by Rick-Kirkham** [comment]
Thanks. This is now fixed.
