### ISSUE TITLE
Add Item to List returning 400: Bad Request

### ISSUE THREAD

**Issue by RicardoSilveira23** [OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations#5]
Line 302, [Default.aspx.cs](https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations/blob/master/SharePoint-Add-in-REST-OData-BasicDataOperationsWeb/Pages/Default.aspx.cs) file.

There is a extra closing bracket that is making the JSON body malformed, producing a 400 Bad Request response when trying to Add an Item to a List.

Fixed with just removing it like this: 
``` 
 //Execute a REST request to add an item to the list.
string itemPostBody = "{'__metadata':{'type':'" + entityTypeName + "'}, 
                                      'Title':'" + newItemName + "'}";
Byte[] itemPostData = System.Text.Encoding.ASCII.GetBytes(itemPostBody);
```

**Comment by Rick-Kirkham** [comment]
Thanks. This is now fixed.
