### ISSUE TITLE
SPRemoteEventProperties could not be found

### ISSUE THREAD

**Issue by mcqueene** [OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations#6]
Probably something stupid on my part but tried to add reference to Microsoft.SharePoint.Client.EventReceivers and that isn't found. Checked documentation for that namespace and I don't see that it was depreciated.

**Comment by mmmiller73** [comment]
I am having the same issue with SPO.

**Comment by flafson** [comment]
You need to add a reference for Microsoft.SharePoint.Client and Microsoft.SharePoint.Client.Runtime.
If you don't have those DLLs, I had to install SharePoint SDK from Microsoft and then browsed to those 2 files.

**Comment by VesaJuvonen** [comment]
Closing as answered before archiving the repository.
